### ISSUE TITLE
Config.class

### ISSUE THREAD

**Issue by cooffeeRequired** [Sashie/Horadric-Cube#2]
May i add also the Configuration class same as SkJson has https://github.com/cooffeeRequired/skJson/blob/main/src/main/java/cz/coffee/skjson/api/Config.java
for loading config.yml etc. ?

**Comment by Sashie** [comment]
There are a few things that should/could be in a separate utils class but otherwise i dont see why we couldn't add this!

Slap some good comments in there ;)

**Comment by cooffeeRequired** [comment]
I think it would be nice to make some adjustments in terms of clarity, and play around with it a bit more.
